name: fluttermodule
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_boost: ^1.12.13+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.zc.fluttermodule
    iosBundleIdentifier: com.zc.fluttermodule
